org.gradle.jvmargs = -Xmx4096M
org.gradle.daemon = false


# Mc stuff
minecraft_version = 1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.22

java_version = 21

enabled_platforms = fabric,neoforge
pack_format_number = 25

# Mod stuff
mod_id = advancementframes
mod_name = Advancement Frames
mod_version = 1.21-2.2.9
release_type = release
mod_license = Supplementaries Team License v.1.1
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar
mod_description = Display your hard earned advancements & stats in style!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/advframes
mod_github = https://github.com/MehVahdJukaar/advframes
mod_credits = MehVahdJukaar, Plantkillable

project_id = 556795


# Loaders
parchment_version = 1.20.6:2024.06.16

fabric_loader_version = 0.15.11
fabric_api_version = 0.100.3+1.21

neo_version = 21.1.71
neo_version_range = [4,)
loader_version_range = [4,)

# Other deps
moonlight_version = 1.21-2.14.18a
moonlight_version_range = 1.21-2.14.0















