# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = advancementframes
mod_name = Advancement Frames
mod_version = 26.1.2-3.0.0
mod_author = MehVahdJukaar
mod_description = Display your hard earned advancements & stats in style!
mod_license = Supplementaries Team License v.1.1
mod_authors = MehVahdJukaar
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/advframes
mod_credits = MehVahdJukaar, Plantkillable
mod_github = https://github.com/MehVahdJukaar/advframes

release_type = beta
maven_group = net.mehvahdjukaar

# Publishing
repository = MehVahdJukaar/advframes
modrinth_project_id = advancement-frames
curseforge_project_id = 556795

# MC / loader versions
java_version = 25
mc_version = 26.1.2

neoforge_version = 26.1.2.94
# NFRT 2.0.18 bundled by the convention plugin can't compile with --release 25
neoForge.neoFormRuntime.version = 2.0.25

fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.1.2

# Other deps
moonlight_version = 26.1.2-4.0.7
moonlight_min_version = 26.1.2-4.0.7
codecui_version = 26.1.2-1.4.3
